# Generated by Django 5.1.4 on 2025-02-02 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('sex', models.CharField(blank=True, default='N', max_length=1)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'dni'], name='account_cli_user_id_0a8062_idx')],
            },
        ),
    ]
