# Generated by Django 5.2.6 on 2025-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.PositiveSmallIntegerField(blank=True, default=0, max_length=10),
        ),
    ]
