# Generated by Django 5.2.6 on 2025-09-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_client_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
