# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        verbose: true
    -   id: end-of-file-fixer
        verbose: true
    -   id: check-yaml
        verbose: true
    -   id: check-added-large-files
        verbose: true
-   repo: local
    hooks:
    -   id: run-tests
        name: "🧪 Django Tests"
        entry: uv run run_tests.py
        language: system
        types: [python]
        stages: [pre-commit]
        verbose: true
        pass_filenames: true
    -   id: run-linter
        name: "🧹 Ruff Linting"
        entry: uv run run_ruff.py
        language: system
        types: [python]
        stages: [pre-commit]
        verbose: true
        pass_filenames: true
