services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /scripts/start.sh
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env.docker
    image: e-commerce-image
    container_name: web-container
  db:
    image: postgres
    container_name: db-container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # Allow any conexions
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432

volumes:
  postgres_data:
    driver: local
