[pkgs]
apt = ["default-libmysqlclient-dev", "build-essential", "pkg-config"]

[env]
NIXPACKS_UV_VERSION = "0.4.30"

[deploy]
command = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install uv==$NIXPACKS_UV_VERSION && uv sync --no-dev --frozen"
