# Generated by Django 5.1.4 on 2025-02-02 00:53

import django.db.models.deletion
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fundator', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='brands')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['name', 'fundator'], name='web_brand_name_dbb0e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['name'], name='web_categor_name_e51bae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='No description for this product')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='products')),
                ('weight', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('dimension', models.CharField(blank=True, default='N/A', max_length=50)),
                ('color', models.CharField(blank=True, default='N/A', max_length=50)),
                ('brand', models.ForeignKey(blank=True, default=web.models.get_default_brand, on_delete=django.db.models.deletion.RESTRICT, to='web.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['title', 'category'], name='web_product_title_313a87_idx')],
            },
        ),
    ]
