# Generated by Django 5.1.4 on 2025-01-12 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('sex', models.CharField(blank=True, default='N', max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('order_num', models.CharField(max_length=20, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('0', 'Pendings'), ('1', 'Paid')], default='0', max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.client')),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.product')),
            ],
            options={
                'verbose_name': 'OrderDetail',
                'verbose_name_plural': 'OrdersDetail',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'dni'], name='web_client_user_id_ca44f4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'registration_date', 'status'], name='web_order_client__69dcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['order'], name='web_orderde_order_i_9141ff_idx'),
        ),
    ]
