# Generated by Django 5.1.4 on 2025-02-02 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('order_num', models.CharField(blank=True, default='0000', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('0', 'Pendings'), ('1', 'Paid')], default='0', max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.client')),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_details', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_details', to='web.product')),
            ],
            options={
                'verbose_name': 'OrderDetail',
                'verbose_name_plural': 'OrdersDetail',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'registration_date', 'status'], name='order_order_client__7c53b0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['order'], name='order_order_order_i_ec1c02_idx'),
        ),
    ]
