# Generated by Django 5.1.4 on 2025-04-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Order Detail', 'verbose_name_plural': 'Orders Detail'},
        ),
    ]
