# Generated by Django 5.2.6 on 2025-09-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
