# Generated by Django 6.0 on 2025-12-30 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_client_phone'),
        ('order', '0005_alter_order_total_price_alter_orderdetail_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='account.client'),
        ),
    ]
